name: Run fetch_arxiv.py


on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout out-pages branch
      uses: actions/checkout@v3
      with:
        ref: out-pages

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run fetch_arxiv.py to generate HTML
      run: python fetch_arxiv.py config.json

    - name: Commit and Push changes
      run: |
        git add -A
        git diff-index --quiet HEAD || git commit -m "Update generated HTML"
        git push origin out-pages
