name: Debug Cron

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes for testing
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print current time
        run: date -u
      - name: Trigger info
        run: echo "Triggered by ${{ github.event_name }}"
